// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Routines.Api.Database;

#nullable disable

namespace Routines.Api.Migrations
{
    [DbContext(typeof(RoutinesDbContext))]
    [Migration("20250213135154_UpdateUsersTableRemoveDateOfBirth")]
    partial class UpdateUsersTableRemoveDateOfBirth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Routines.Api.Domain.Action", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("FollowUpActionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("RoutineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FollowUpActionId");

                    b.HasIndex("RoutineId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("Routines.Api.Domain.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("FollowUpRoutineId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FollowUpRoutineId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("Routines.Api.Domain.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Intervals")
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("RoutineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Routines.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Routines.Api.Domain.Action", b =>
                {
                    b.HasOne("Routines.Api.Domain.Action", "FollowUpAction")
                        .WithMany()
                        .HasForeignKey("FollowUpActionId");

                    b.HasOne("Routines.Api.Domain.Routine", "Routine")
                        .WithMany("Actions")
                        .HasForeignKey("RoutineId");

                    b.Navigation("FollowUpAction");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("Routines.Api.Domain.Routine", b =>
                {
                    b.HasOne("Routines.Api.Domain.Routine", "FollowUpRoutine")
                        .WithMany()
                        .HasForeignKey("FollowUpRoutineId");

                    b.HasOne("Routines.Api.Domain.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("FollowUpRoutine");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Routines.Api.Domain.Schedule", b =>
                {
                    b.HasOne("Routines.Api.Domain.Routine", null)
                        .WithMany("Schedules")
                        .HasForeignKey("RoutineId");
                });

            modelBuilder.Entity("Routines.Api.Domain.Routine", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
