version: '3.9'

services:

  api:
    build: .
    ports:
      - "5101:443"
      - "5100:80"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test1234!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - ASPNETCORE_Environment=Production
      - RoutinesApi_Database__ConnectionString=Server=db;Port=5432;Database=routinesdb_local;User ID=routinesdb_local;Password=P@ssw0rD;
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=routinesdb_local
      - POSTGRES_PASSWORD=P@ssw0rD
      - POSTGRES_DB=routinesdb_local
    ports:
      - '5432:5432'
